theme: jekyll-theme-minimal
title: MRC DTP Symposium 2025
description: >-
  A one-day scientific symposium bringing together students and researchers
  in the Medical Research Council Doctoral Training Partnership. Featuring keynote speakers, student talks, poster sessions, and a formal dinner.
