title: MRC DTP Symposium 2025
baseurl: "/MRC-DTP-Symposium-2025"
url: "https://mrc-dtp.github.io"
description: >-
  A one-day scientific symposium bringing together students and researchers
  in the Medical Research Council Doctoral Training Partnership. Featuring keynote speakers, student talks, poster sessions, and a formal dinner.
